import { term2Exams, type Term2ExamId } from "@/src/lib/mcq/exams.mjs";

const sources = [
  { subject: "Anatomy", book: "Gray’s Anatomy for Students · 3rd edition", chapters: "Chapter 3: respiratory core (printed pp. 161–179); Chapter 8: pharynx, larynx and nasal cavities (pp. 1040–1087). Book-only extensions: respiratory framework pp. 150–155 and surface anatomy pp. 238–240.", slides: "11 local anatomy decks: Nasal Bones 1–4, LARYNX 1–4, Trachea and lung 1–3. Extra book-only pages are not claimed as teacher-confirmed scope.", status: "Book + slides" },
  { subject: "Histology", book: "Junqueira’s Basic Histology · 16th edition", chapters: "Chapter 17: The Respiratory System · printed pages 349–369", slides: "Text and micrographs from the book. No transcript-derived questions in this bank.", status: "Book + micrographs" },
  { subject: "Embryology", book: "Langman’s Medical Embryology · 15th edition", chapters: "Chapter 14: Respiratory System · printed pages 225–231", slides: "Local respiratory embryology decks E1 and E2", status: "Book + slides" },
  { subject: "Physiology", book: "Guyton and Hall · 15th edition (2026)", chapters: "38 Ventilation · 39 Pulmonary circulation · 40 Gas exchange · 41 Gas transport · 42 Regulation of respiration", slides: "Respiratory physiology teacher slides have not been found. These questions are explicitly book-only.", status: "Book-only" },
];

export function Term2Guide({ exam, compact = false }: { exam: Term2ExamId; compact?: boolean }) {
  const definition = term2Exams.find((item) => item.id === exam)!;
  if (exam === "term2-divine-ethics") return <aside className="term2-notice"><b>Your new course extract → notes → focused MCQs</b><p>Study concepts contains nine teaching modules and the updated review PDF. Topics offers 75 newly authored practice questions with page references and explanations for every option.</p><small>The scan contains 12 teaching pages and 3 contents pages, not every chapter listed. Older packet material is labeled separately in the PDF. No genuine past-paper bank has been supplied.</small></aside>;
  if (exam === "term2-religion") return <aside className="term2-notice"><b>Review-based practice · original papers in Final Exam</b><p>Open Topics for 25 source-mapped teaching sets. The review combines available lecture material, matched chapters of Theological Instructions, and separately identified biography, scripture and ethics references.</p><small>Final Exam retains all 180 source occurrences. Editorial keys are not official university answers. Repeated, disputed and unresolved items remain in All papers with explanations; they are not silently discarded or forced into scored questions.</small></aside>;
  if (exam === "term2-nutrition") return <aside className="term2-notice"><b>Practice from the review/book · Final Exam from past papers only</b><p>Practice follows Nutrition Review sections 02–24 and DeBruyne, Pinna & Whitney’s Nutrition & Diet Therapy, 9th edition (2016). Topic cards link to focused question sets. Final Exam preserves original downloaded questions and choices, with English translations where needed and checked explanations.</p><small>Marked answers are not an official key. Ambiguous, cropped and unsupported past-paper items are withheld. Oral-health practice is a labeled book supplement, not confirmed exam scope. No Nutrition lecture slides or official exam blueprint have been confirmed.</small></aside>;
  if (exam === "term2-physiology-practical") return <aside className="term2-notice"><b>Watch → understand → rehearse → test</b><p>Nine practical stations from the local WhatsApp pack and ECG assignment. Open Practical lessons for source images, demonstrations, procedure reasoning, calculations and linked MCQs. Invasive procedures require supervised laboratory practice.</p><small>31 August 2026: user-reported date, not an official timetable. Source coverage is not an exam guarantee. YouTube is supplementary; source corrections are explicitly flagged.</small></aside>;
  if (exam !== "term2-respiratory" && definition.status === "ready") return <aside className="term2-notice"><b>Source map → active recall → focused practice</b><p>{definition.scope}. Open Study concepts to see the reconciled course/book boundary, module notes, retrieval prompts and linked verified questions.</p><small>Source-based practice is kept separate from Past Exams. Exam date and official weighting remain unconfirmed.</small></aside>;
  if (exam !== "term2-respiratory") return <aside className="term2-notice"><b>Exam section created · independent verification in progress</b><p>{definition.scope}. No Term 1 questions have been relabeled as Term 2.</p><small>Exam date: awaiting confirmation.</small></aside>;
  if (compact) return <aside className="term2-notice"><b>Understand → recall → answer → explore</b><p>Open Study concepts for detailed theory, retrieval prompts and objective-linked MCQs. Every answer includes an explanation and source locator. Anatomy labels unlock after answering; in closed-book test mode they wait until grading. Each session uses only one variant per anatomical target.</p><small>Date TBA · physiology is book-only · source coverage is not an official exam blueprint. Visual Guide contains the book/chapter reading map.</small></aside>;
  return <section className="term2-source-guide"><p className="eyebrow">Respiratory · Source & reading map</p><h2>Read the theory. Then test it.</h2><p>Use these specific editions: chapter numbers differ from the older syllabus references. This bank does not use past papers, web question banks or video transcripts.</p><div className="source-map">{sources.map((source) => <article key={source.subject}><div><span>{source.subject}</span><small>{source.status}</small></div><h3>{source.book}</h3><p>{source.chapters}</p><small>{source.slides}</small></article>)}</div><p className="term2-scope-note">Coverage means these source topics are represented, not that every possible question or teacher emphasis is covered. The exact exam date and final blueprint remain unconfirmed. Physiology clinical extensions beyond Chapters 38–42 are not included.</p></section>;
}
