"""One-time, idempotent source-based expansion of the private review authoring JSON.

Original notes/slide/book PDFs are read-only. The first run preserves the pre-audit
authoring JSON and PDF. Use the existing private _build/build.py to render afterward.
"""
import json, shutil
from pathlib import Path

ROOT = Path('/Users/rizzist/Documents/MED SLIDES/TERM 2/10 Review Summaries')
BUILD = ROOT / '_build'
SOURCE = BUILD / 'content/biochemistry.json'
BACKUP = BUILD / 'audit/biochemistry-before-past-paper-audit-2026-09-23'
BACKUP.mkdir(parents=True, exist_ok=True)
if not (BACKUP / 'biochemistry.json').exists():
    shutil.copy2(SOURCE, BACKUP / 'biochemistry.json')
    shutil.copy2(ROOT / '04 - Biochemistry II Review.pdf', BACKUP / 'review.pdf')
v = json.loads((BACKUP / 'biochemistry.json').read_text())
sections = {s['id'].removeprefix('biochem-'): s for s in v['sections']}
BOOK = "/Users/rizzist/Documents/MED SCHOOL BOOKS/Biochemistry [Lippincott's Illustrated Reviews Series] Denise R. Ferrier PhD.pdf"
GUYTON = '/Users/rizzist/Documents/MED SCHOOL BOOKS/Guyton and Hall Textbook of Medical Physiology (2026).pdf'
CARBS = '/Users/rizzist/Documents/MED SLIDES/BIOCHEM/05 Metabolism/carbohydrate metabolism MD Kish.pdf'
LIPIDS = '/Users/rizzist/Documents/MED SLIDES/BIOCHEM/05 Metabolism/Lipid metabolism 1.pdf'
ENZYMES = '/Users/rizzist/Documents/MED SLIDES/BIOCHEM/03 Enzymes/Enzyme Kinetics and regulation session 2.pdf'

def p(text): return {'type':'paragraph','text':text}
def table(headers, rows): return {'type':'table','headers':headers,'rows':rows}
def box(title, text, kind='trap'): return {'type':'callout','kind':kind,'title':title,'text':text}
def book(pages): return {'title':'Lippincott Illustrated Reviews: Biochemistry, Ferrier, 6th edition','path':BOOK,'locator':'PDF '+pages}
def guyton(pages): return {'title':'Guyton and Hall Textbook of Medical Physiology (local 2026 PDF)','path':GUYTON,'locator':'PDF '+pages}
def online(title, url): return {'title':title,'url':url,'locator':'Accessed 23 September 2026; supplemental clinical verification'}
def add(id, blocks, sources=()):
    sections[id]['blocks'].extend(blocks)
    sections[id]['sources'].extend(sources)
def new(id, title, blocks, sources):
    s={'id':'biochem-'+id,'title':title,'basis':'past-paper gap audit + book/reference extension','sources':sources,'blocks':blocks}
    sections[id]=s; v['sections'].append(s)

v['updated']='23 September 2026'
v['scope']='Lecture- and book-grounded metabolism review expanded against 641 source-question occurrences in 14 supplied past-paper collections and one separately labelled reconstruction. Core pathways are retained; new material covers diagnostic enzymes, liver and renal biochemistry, endocrine signaling and detailed metabolic disorders. The original carbohydrate and first lipid slide decks were located in the wider BIOCHEM folder during this audit. Clinical extensions are distinguished from confirmed lecture content. This is coverage of the available material, not an official examination blueprint or a guarantee of future exam coverage.'
v['sourceFiles']=list(dict.fromkeys(v['sourceFiles']+[CARBS,LIPIDS,ENZYMES,GUYTON]))
v['gaps']=[
 'The full 103-page carbohydrate slide PDF and 42-page first lipid slide PDF were located in BIOCHEM/05 Metabolism during the September 2026 audit; the earlier claim that the carbohydrate deck was unavailable is superseded.',
 'Later Term 2 lipid, nitrogen, nucleotide, endocrine and clinical-diagnostic lecture decks have not been established in the supplied files. Relevant past-paper topics are now taught using the inspected books and explicitly cited supplementary clinical references, not falsely attributed to a missing lecture.',
 'The 15 collections contain 641 question occurrences, not 641 independent concepts. One collection is an unauthenticated reconstruction. Twenty-three flawed or unresolved items remain ungraded; their ambiguity must not be converted into a false biological rule.',
 'The local Ferrier file is 6th edition, whereas the lipid lecturer refers to 7th edition. Modern and historical ATP accounting and cardiac-marker conventions are distinguished.',
 'Coverage has been checked against available source questions and the available lecture/book topics. Missing lecture files and future examination content cannot be certified complete. Read original images and qualifiers alongside the synthesis.'
]
add('source-map',[
 box('September 2026 coverage update','The new audit adds the previously absent clinical-diagnostic and endocrine topics and expands fine biochemical mechanisms. The row-level audit records a review destination for every source occurrence, including a separate warning for each of the 23 ungraded items. A destination means the underlying concept is taught; it does not authenticate the source answer key.','key'),
 p('Newly found lecture evidence: carbohydrate metabolism MD Kish.pdf, 103 pages; Lipid metabolism 1.pdf, 42 pages; and the 41-page enzyme kinetics/regulation PDF. The first two agree with the available metabolism recordings and supply the original diagrams. The enzyme deck is supporting course material, not proof that every clinical enzyme test was lectured in Term 2.')
],[{'title':Path(CARBS).name,'path':CARBS,'locator':'PDF pp. 1-103; pathway and regulation cross-check'},{'title':Path(LIPIDS).name,'path':LIPIDS,'locator':'PDF pp. 1-42; lipid digestion, chylomicrons and disorders'}])
# Correct the old source map instead of leaving contradictory availability claims.
for b in sections['source-map']['blocks']:
    if b['type']=='paragraph' and b['text'].startswith('Use the lecture-supported'):
        b['text']='Use the lecture-supported carbohydrate and dietary-lipid sections first. Original slide PDFs, reconstructed notes and recordings are now cross-referenced. Book/reference extensions supply clinical comparisons tested in the supplied papers. Their inclusion establishes coverage of those questions, not of an unseen official syllabus. Raw transcripts are preserved, with transcription errors corrected in the synthesis.'
    if b['type']=='table':
        b['rows'][0][1]='103-page original carbohydrate PDF, two note sets and three carbohydrate recordings'
        b['rows'][2][1]='42-page original lipid PDF and three parts of Esmaeili lipid lecture 1'
        b['rows'][5][1]='Book extension; confirmed question themes in supplied past papers'

add('glycolysis-regulation',[
 p('The Rapoport-Luebering branch uses bisphosphoglycerate mutase to form 2,3-BPG from 1,3-BPG, then bisphosphoglycerate phosphatase to form 3-phosphoglycerate. It bypasses phosphoglycerate kinase and sacrifices one ATP per diverted triose. Phosphoglycerate kinase is reversible: it produces ATP in glycolysis and consumes ATP in gluconeogenesis.'),
 box('Lactate is not simply a poison','Lactate production regenerates NAD+ and can continue even when oxygen is present. Exercise fatigue is multifactorial; lactate alone is not the cause of delayed muscle soreness. Some old MCQs use an oversimplified lactate/fatigue association. Fluoride inhibits enolase; arsenate uncouples ATP capture at the GAP-dehydrogenase/phosphoglycerate-kinase sequence, whereas arsenite principally inhibits lipoate-dependent complexes.')
],[book('pp. 189-207'),{'title':Path(CARBS).name,'path':CARBS,'locator':'PDF pp. 8-26'}])
add('oxphos',[
 table(['Component','Recognize','Reasoning'],[
 ['Complex I','NADH dehydrogenase: FMN and Fe-S centers','Accepts NADH electrons; pumps H+.'],
 ['Complex II','Succinate-Q reductase: FAD and Fe-S centers','No proton pumping; feeds electrons to Q.'],
 ['Complex III / IV','Cytochromes b/c1 / cytochromes a and a3 with copper centers','Cytochrome c transfers one electron; Q can carry two electrons and protons. O2 is the final acceptor at IV.'],
 ['ATP synthase / ANT','Oligomycin blocks F0; atractyloside blocks the ADP/ATP translocator','ANT exchanges cytosolic ADP for matrix ATP; it is not itself an ETC complex.'],
 ['Proton motive force','Membrane voltage plus a pH gradient','The inner membrane must restrict nonspecific ion flow. A freely permeable membrane cannot sustain coupled ATP synthesis.']]),
 p('Electron flow generally proceeds toward more positive reduction potential. Of FMN and the downstream carriers used in these papers, FMN is the relatively weak oxidant; NADH upstream has still lower reduction potential. Do not interpret the MCQ as claiming FMN is the lowest-potential substance in all biology. Dehydrogenases transfer electrons to cofactors and do not all use molecular oxygen directly.'),
 table(['Accounting question','Modern convention','Historical convention'],[
 ['One acetyl-CoA in TCA','3(2.5) + 1(1.5) + 1 = 10 ATP','3(3) + 1(2) + 1 = 12 ATP'],
 ['Alpha-ketoglutarate to succinate','One NADH + one GTP = 3.5 ATP equivalents','4 ATP equivalents'],
 ['Highest phosphate-transfer potential among usual options','PEP exceeds 1,3-BPG, phosphocreatine and ATP','Use the actual listed compounds; ATP is not the highest-energy phosphate.']])
],[book('pp. 143-155')])
add('glycolysis-regulation',[
 p('For the paired hemolysis/acidosis question, pyruvate-kinase deficiency lowers RBC ATP and causes hemolytic anemia. The mercury option invokes the traditional teaching model of sulfhydryl-enzyme interference with pyruvate oxidation. Mercury species and experimental conditions matter: methylmercury studies also show altered mitochondrial pyruvate transport, not uniformly strong PDH inhibition. Do not turn that exam association into a mercury-specific clinical diagnostic rule. Thiamine deficiency and inherited PDH defects are clearer mechanisms for pyruvate/lactate accumulation.')
],[online('Alexandria National University: Medical Biochemistry Unit, oxidative decarboxylation teaching note','https://medportal.anu.edu.eg/moodledata/filedir/4e/92/4e929053b3f6ed5251a83e21ed7a3b38bd2c8612'),online('Transport of pyruvate into mitochondria is involved in methylmercury toxicity (cell study)','https://www.nature.com/articles/srep21528')])
add('cholesterol',[],[online('Mevalonate kinase deficiency with mevalonic aciduria: biochemical case evidence','https://pubmed.ncbi.nlm.nih.gov/2850914/')])
add('glucose-entry',[p('At the intestinal brush border, sucrase releases glucose plus fructose, lactase releases glucose plus galactose, and maltase releases glucose. SGLT1 handles apical glucose/galactose, GLUT5 apical fructose, and GLUT2 basolateral exit. Renal glucose reabsorption uses sodium-coupled transport, not insulin-controlled GLUT4. In diabetes the filtered load can exceed the transport maximum and cause glycosuria: insulin independence does not mean renal glucose handling is clinically unchanged.')],[book('pp. 176-187')])
add('other-sugars',[p('Differentiate GLUT5-related fructose malabsorption (impaired intestinal entry) from hereditary fructose intolerance (aldolase B deficiency inside cells). In the latter, fructose-1-phosphate traps phosphate, ATP falls, AMP degradation can raise urate, and hepatic glucose output is impaired. Classic galactosemia similarly accumulates galactose-1-phosphate and may cause hypoglycemia and hepatic injury; galactokinase deficiency is usually dominated by cataracts. Aldose reductase consumes NADPH to make sorbitol from glucose or galactitol from galactose. The lens has inadequate sorbitol dehydrogenase to clear the load. Polyol accumulation and nonenzymatic advanced glycation end products are different processes, not interchangeable carbohydrate names.')],[book('pp. 230-245')])
add('glycogen',[p('Von Gierke disease combines fasting hypoglycemia with hepatomegaly, lactic acidosis, hyperlipidemia and often hyperuricemia, not hypouricemia. McArdle disease is a muscle defect: exercise cramps and myoglobinuria can occur, but hepatomegaly is not its defining pattern. In plant carbohydrate synthesis, ADP-glucose supplies starch, whereas UDP-glucose supplies cellulose; neither should be silently substituted for the other when a paper omits the correct option.')],[{'title':Path(CARBS).name,'path':CARBS,'locator':'PDF pp. 35-37 and carbohydrate biosynthesis slides'},book('pp. 246-265')])
add('beta-oxidation',[p('For saturated even chains, C14 requires six cycles and C18 eight. Water is consumed during hydration, not generated as a net beta-oxidation product; neither NADPH nor malonyl-CoA is a product. In conventional odd-chain bookkeeping, C17 gives seven acetyl-CoA plus propionyl-CoA. Counting propionyl-CoA to oxaloacetate gives 5 ATP equivalents minus 1 ATP for carboxylation; total C17 yield is 7(10)+7(4)+4-2=100, compared with 106 for C16. C13 similarly gives 72 versus 78 for C12. This is a stated bookkeeping endpoint, not complete oxidation of all propionyl carbon to CO2 or a universal calorimetry rule. Unsaturated fatty acids yield less than a saturated chain of the same length; multiple double bonds further alter the accounting.'),p('Zellweger-spectrum peroxisome-biogenesis disorders impair very-long-chain fatty-acid oxidation and other peroxisomal functions, not primarily short-chain mitochondrial oxidation. Refsum disease impairs alpha-oxidation of phytanic acid. Carnitine is necessary for long-chain mitochondrial import, but knowing that mechanism does not establish benefits from taking carnitine supplements in an otherwise replete person.')],[book('pp. 352-366')])
add('fatty-acid-synthesis',[p('Humans can introduce a delta-9 double bond but cannot synthesize the omega-6/omega-3 parent fatty acids through delta-12/delta-15 desaturation. Metformin can favor AMPK-mediated ACC inhibition; cAMP-linked counterregulatory signaling also favors inhibition. These are regulatory pathways, not proof of direct binding of those signals to the ACC catalytic site. Malonyl-CoA is needed for fatty-acid synthesis, not the cholesterol pathway.')],[book('pp. 340-351')])
add('complex-lipids',[p('Anti-inflammatory glucocorticoids reduce arachidonate/eicosanoid availability partly through annexin-mediated restraint of phospholipase A2 and altered gene expression. This differs from aspirin acting at cyclooxygenase. Neither statement means all inflammatory mediators use the same pathway.')],[book('pp. 401-404')])
add('lipid-digestion',[p('Orlistat inhibits gastric and pancreatic lipases. Gallbladder bile supplies bile salts but is not the source of pancreatic enzymes; conversely, pancreatic juice does not supply bile salts. Aldolase is a glycolytic enzyme, not a pancreatic digestive hydrolase. CCK promotes enzyme release and gallbladder contraction while slowing gastric emptying; secretin mainly promotes pancreatic bicarbonate release.')],[{'title':Path(LIPIDS).name,'path':LIPIDS,'locator':'PDF pp. 4-19'}])
add('cholesterol',[p('Count isoprene carbons: C5 isopentenyl-PP plus its C5 dimethylallyl isomer gives C10 geranyl-PP; addition of another C5 gives C15 farnesyl-PP; two C15 units form C30 squalene. Farnesyl/prenyl groups anchor proteins to membranes; this pathway also supplies nonsterol isoprenoids such as dolichol and ubiquinone. Smith-Lemli-Opitz syndrome is a DHCR7 defect with increased 7-dehydrocholesterol and often low cholesterol. Mevalonate-kinase deficiency blocks phosphorylation downstream of mevalonate and can cause mevalonic aciduria. These pathway markers are established; the rare hematologic distinctions proposed in two supplied questions were not verified and remain withheld.'),p('A net hepatic cholesterol influx greater than efflux means accumulation; it does not by itself identify cholestasis, steatosis or a unique clinical disease. Steroid side-chain cleavage makes pregnenolone from cholesterol. Testosterone-to-dihydrotestosterone conversion requires 5-alpha-reductase, distinct from aromatase conversion of androgens to estrogens.')],[book('pp. 410-414; 433-447')])
add('lipoprotein-map',[
 table(['Pattern','Main particles / mechanism','Exam distinction'],[
 ['Fredrickson I','Chylomicrons; LPL or apoC-II deficiency','Marked TAG, eruptive xanthomas and pancreatitis; tendon xanthomas point more toward LDL excess.'],
 ['IIa / IIb','LDL alone / LDL plus VLDL','IIa classically LDL-receptor or apoB-100 related; HDL does not have to be low.'],
 ['III','Remnant particles; impaired apoE-dependent clearance','Both cholesterol and TAG rise; palmar or tuberoeruptive xanthomas suggest it.'],
 ['IV / V','VLDL / VLDL plus chylomicrons','TAG-predominant patterns, with differing particle contributions.'],
 ['Tangier / apoB assembly failure','ABCA1-dependent efflux defect / MTP-dependent apoB particle assembly defect','Tangier: extremely low HDL. ApoB-48 assembly failure: fat malabsorption, not the classic LDL-clearance disorder.']]),
 p('Nascent VLDL contains apoB-100; nascent HDL depends on apoA-I. Hepatic lipase helps convert IDL to LDL. Chylomicrons have the highest TAG fraction and LDL the highest cholesterol fraction among the usual choices. HDL carries peripheral cholesterol toward liver; it is not the principal liver-to-periphery cholesterol carrier. Its LCAT reaction uses phosphatidylcholine, unlike ACAT. Post-meal chylomicrons can make plasma milky; persistent fasting chylomicronemia is different.'),
 p('Insulin resistance commonly combines higher TAG, lower HDL and small dense LDL particles; LDL cholesterol itself need not be high. Hypothyroidism commonly raises LDL by reducing clearance, and HDL changes are variable rather than obligatorily low. Replacing saturated fat with polyunsaturated fat generally lowers LDL, but this is a dietary pattern statement, not an individual treatment prescription.')
],[book('pp. 420-432; 635-650')])
add('protein-nitrogen',[p('Specify the membrane: many apical amino-acid carriers are sodium coupled, while basolateral release toward portal blood commonly uses facilitated carriers/exchange systems. A question about release into portal blood is not asking how amino acids first enter the brush border. Peptides can enter through proton-coupled transport and then be hydrolyzed. Proelastase, trypsinogen and chymotrypsinogen are zymogens. Glutamine synthetase uses ATP and free ammonia; asparagine synthetase uses ATP and generally glutamine amide nitrogen. Glutamate dehydrogenase can use NAD+ or NADP+; reductive amination commonly uses NADPH.')],[book('pp. 448-462')])
add('aa-disorders',[p('Hartnup disease affects neutral amino-acid transport in intestine and kidney, including tryptophan and phenylalanine. Loss of tryptophan limits niacin synthesis and can produce pellagra-like dermatitis and neurologic features. It differs from cystinuria, which affects cystine and dibasic amino acids. Tyrosinemia II is tyrosine aminotransferase deficiency: corneal pseudodendritic lesions and palmoplantar skin lesions distinguish it from type I liver/renal disease; eye lesions may resemble herpes keratitis. PKU causes phenylalanine accumulation and tyrosine deficiency, not a typical cirrhotic-liver presentation.'),p('BH4 is synthesized from GTP and is required by phenylalanine, tyrosine and tryptophan hydroxylases and nitric-oxide synthase. Dopamine beta-hydroxylase instead requires copper and ascorbate. Arginine is conditionally essential during growth or some illnesses. In classic CBS-deficient homocystinuria, homocysteine and methionine often rise; remethylation defects differ. MSUD neurotoxicity involves leucine and branched-chain ketoacids. The maple odor is associated with sotolon but odor alone cannot establish the defect or justify unsupported EXCEPT lists.')],[book('pp. 477-505; 521-527'),online('GeneReviews: Tyrosinemia Type II','https://www.ncbi.nlm.nih.gov/books/NBK608431/')])
add('urea',[p('OTC deficiency is the common inherited urea-cycle disorder and is X-linked, whereas CPS-I deficiency is a different early block. Arginase deficiency produces hyperargininemia. The fumarate-to-malate-to-oxaloacetate/aspartate connection joins nitrogen disposal with TCA chemistry. In advanced liver failure, ammonia-to-urea disposal falls; a low urea value is not automatically evidence of excellent renal filtration.')],[book('pp. 463-476')])
add('gluconeogenesis',[box('Corrections to the newly recovered carbohydrate slides','The carbohydrate deck p. 53 loosely places gluconeogenesis in liver and muscle. Muscle can metabolize lactate but lacks the glucose-6-phosphatase system needed for net free-glucose export. Liver and kidney are the relevant glucose-producing organs. Page 54 also overgeneralizes conversion of all precursors to pyruvate: glycerol enters at DHAP and several amino acids enter through other intermediates.')],[{'title':Path(CARBS).name,'path':CARBS,'locator':'PDF pp. 38-54; source wording compared with Ferrier ch. 10'}])
add('special-products',[p('Creatine synthesis uses glycine and arginine plus a methyl group donated by methionine through SAM. Kidney and liver are major contributors, but brain can also synthesize creatine. Creatine/phosphocreatine spontaneously cyclize to creatinine; do not mistake creatinine for the ATP-buffering substrate phosphocreatine. Nitric oxide activates soluble guanylyl cyclase and increases cGMP, favoring smooth-muscle relaxation rather than contraction.')],[book('pp. 521-527')])
add('heme',[
 table(['Disorder','Mechanism','Bilirubin pattern'],[
 ['Gilbert','Partial reduction in UGT1A1 activity','Mild intermittent unconjugated rise; no bilirubinuria. A fixed decrease in urine urobilinogen is not diagnostic.'],
 ['Crigler-Najjar I / II','Absent / markedly reduced conjugating activity','Severe / less severe unconjugated hyperbilirubinemia; reduced pigment delivery to gut in severe conjugation failure.'],
 ['Dubin-Johnson','Canalicular conjugated-bilirubin export defect','Conjugated hyperbilirubinemia; distinguish it from UGT1A1 failure.'],
 ['Neonatal physiologic pattern','High bilirubin load and immature uptake/conjugation','Predominantly unconjugated, not direct hyperbilirubinemia.'],
 ['Hemolysis / complete obstruction','More heme delivery / little bilirubin reaches bowel','Hemolysis: increased urinary urobilinogen. Complete obstruction: little or absent urobilinogen, dark bilirubin-containing urine and pale stools.']]),
 p('Heme oxygenase opens the ring using oxygen and NADPH; biliverdin reductase uses reducing equivalents to form bilirubin. Gut bacteria form urobilinogen from bilirubin; most becomes fecal stercobilin, while some is reabsorbed and a small amount is excreted/oxidized to urinary urobilin. ALAS1 is the broadly expressed hepatic/nonerythroid regulatory isoform; ALAS2 is erythroid, not ubiquitous. CEP often presents early and severely; PCT is the common predominantly acquired cutaneous form. Increased urine ALA supports a lead-related pathway block, but blood lead measurement establishes exposure; a paper offering only urinary ALA does not make it the definitive modern diagnostic test.')
],[book('pp. 507-520')])
add('nucleotides',[
 table(['Ring / compound','Origins or identity','Common trap'],[
 ['Purine N1; N3/N9; C4/C5/N7','Aspartate; glutamine; glycine','Free ammonia does not replace glutamine amide nitrogen in this pathway.'],
 ['Purine C2/C8; C6','N10-formyl-THF; CO2/bicarbonate','Glycine participates in purines, not pyrimidine-ring synthesis.'],
 ['Pyrimidine N1/C4/C5/C6; N3; C2','Aspartate; glutamine; CO2/bicarbonate','Identify the depicted ring before interpreting numbered source labels.'],
 ['IMP / OMP / UMP','First completed purine nucleotide / first ribose-linked pyrimidine nucleotide / product after OMP decarboxylation','OMP and UMP answer different questions. Inosine is hypoxanthine plus ribose, without phosphate.'],
 ['Pyrimidine degradation','Uracil/cytosine to beta-alanine; thymine to beta-aminoisobutyrate','Urate is the human purine endpoint, not a pyrimidine endpoint.']]),
 p('Thioredoxin supplies reducing equivalents to ribonucleotide reductase and is regenerated through NADPH-dependent thioredoxin reductase. Mycophenolic acid inhibits IMP dehydrogenase and lowers GMP synthesis. Allopurinol/oxypurinol inhibit xanthine oxidase, lowering urate and increasing upstream hypoxanthine/xanthine; salvage can reduce de novo flux. Methotrexate blocks DHFR and indirectly limits dTMP and purine synthesis. The 5-fluorouracil metabolite inhibits thymidylate synthase, not an enzyme called thymidine synthase. Sulfonamides block bacterial dihydropteroate synthase upstream of folate-dependent nucleotide production, not human CPS-II directly.'),
 p('Tophi are deposits of monosodium urate in gout; elevated serum urate alone does not prove gout. High cell turnover, impaired renal excretion and thiazides can increase urate. Fanconi proximal-tubular dysfunction can instead waste urate. Do not generalize an EXCEPT option naming non-thiazide antihypertensives to every drug in that broad group. ADA deficiency raises dATP, suppresses DNA precursor production and reduces functional lymphocyte populations; not every SCID is caused by ADA deficiency.')
],[book('pp. 536-555')])
add('insulin-glucagon',[p('Mature insulin contains 51 residues in two chains and THREE disulfide bridges: two between chains and one within the A chain. A question asking total bridges with only two offered is flawed. Endogenous insulin and C-peptide are released together; C-peptide is low in severe beta-cell failure and does not accompany injected insulin. Diazoxide opens beta-cell KATP channels and suppresses secretion; drug-induced diabetes belongs to other specific types. Catecholamine alpha-2 signaling inhibits insulin release during stress. Glucagonoma favors glycogenolysis/gluconeogenesis and inhibits glycogenesis/lipogenesis.'),p('Distinguish early fasting from prolonged starvation: muscle can use ketones but progressively favors fatty acids, conserving ketones for brain. Fed insulin activates adipose LPL and suppresses intracellular HSL-mediated lipolysis. The first delivers lipid from circulating particles; the second mobilizes stored fat. High carbohydrate supply tends to support hepatic VLDL production; prolonged fasting is not equivalent to an uncontrolled diabetic state.')],[book('pp. 562-582; 597-613')])
add('diabetes-integration',[p('Hyperosmolar hyperglycemic state is more typical of type 2 diabetes: profound hyperglycemia and water loss produce hyperosmolality, with relatively restrained ketogenesis. DKA is especially associated with severe insulin deficiency, but overlap exists. Metabolic (Reaven) syndrome combines central adiposity, insulin resistance, high TAG/low HDL, raised pressure and dysglycemia, increasing cardiovascular risk. Acute illness and assay timing matter; neither HHS nor DKA should be diagnosed from a memorized demographic rule alone.')],[book('pp. 614-633')])

new('clinical-enzymes','Diagnostic enzymes, isoenzymes and cardiac/pancreatic markers',[
 p('Separate physiological plasma enzymes from leakage markers. Coagulation enzymes and circulating/endothelial lipoprotein-lipase activity have physiological functions in blood. ALT, AST, LDH and CK ordinarily act inside cells; increased circulating activity can reflect injury. This older functional/nonfunctional terminology describes location of normal action, not whether an enzyme is biologically useful. Isoenzymes catalyze the same reaction but differ in subunits, properties or tissue distribution.'),
 table(['Marker','Main exam association','Qualification'],[
 ['CK / CK-MM / CK-MB / CK-BB','Muscle injury/rhabdomyolysis / skeletal muscle / cardiac-enriched / brain-enriched','CK-MB is not absolutely confined to heart. ALP is not a usual muscle-injury marker.'],
 ['LDH and the flipped ratio','LDH-1 greater than LDH-2: historical myocardial-injury pattern','RBC hemolysis also raises LDH; sample hemolysis can produce misleading results. Reticulocytes, bilirubin and other evidence help distinguish true hemolysis.'],
 ['Cardiac troponin I/T','Myocardial injury, including NSTEMI','Preferred contemporary markers; a rise/fall and ischemic context distinguish MI from other myocardial injury.'],
 ['Myoglobin','Early release from damaged muscle','Older papers call it an early sensitive marker; it is not cardiac specific and is not preferred over modern high-sensitivity troponin.'],
 ['Amylase / lipase','Pancreatic injury; amylase is also salivary','Amylase can enter urine. Lipase is more useful/specific in many current pancreatitis pathways; choose amylase only when it is the best supplied option.'],
 ['Acid phosphatase (ACP)','Prostatic and other isoenzymes; increased bone turnover may contribute','Older broad ACP questions are not modern definitive prostate or liver diagnostic rules. Do not confuse ACP with ALP.']]),
 p('An AST/LDH/CK-MB pattern is a historical cardiac panel. Pulmonary injury and hemolysis can raise LDH without the same cardiac pattern, but a panel alone does not diagnose pulmonary embolism. BNP/NT-proBNP indicate cardiac wall stress and support heart-failure assessment; D-dimer addresses fibrin turnover in an appropriate thromboembolism assessment. They are not interchangeable. Streptokinase promotes plasminogen activation and hence fibrinolysis; it does not directly hydrolyze fibrin as a normal human digestive enzyme.'),
 box('Enzyme tests measure activity under defined conditions','Hemolysis, sampling time, tissue distribution and assay method can change interpretation. A high enzyme concentration is not necessarily proof of injury to the organ named in an MCQ. The word pancreatic-specific is itself too strong for total amylase, which has salivary sources.')
],[book('pp. 128-131'),{'title':Path(ENZYMES).name,'path':ENZYMES,'locator':'PDF pp. 29-41; enzyme regulation and isoenzymes'},online('Cardiac Biomarkers','https://www.ncbi.nlm.nih.gov/books/NBK545216/'),online('Analytical and Clinical Perspectives on Amylase','https://www.ncbi.nlm.nih.gov/books/NBK557738/'),online('Biochemistry, Lactate Dehydrogenase','https://www.ncbi.nlm.nih.gov/books/NBK557536/')])
new('liver-tests','Liver injury, cholestasis and synthetic-function patterns',[
 table(['Pattern','Evidence','Reasoning'],[
 ['Hepatocellular injury','ALT/AST predominate','ALT is more liver-enriched, not liver-exclusive; AST also occurs in heart, muscle and RBCs.'],
 ['Cholestatic pattern','ALP with GGT or 5-prime-nucleotidase','Supports hepatobiliary origin; obstruction, PBC and PSC are examples, not a diagnosis from one number.'],
 ['Bone-related ALP','ALP elevated with no parallel GGT rise','Consider skeletal growth, Paget disease or other bone turnover; interpret age and pregnancy.'],
 ['Synthetic impairment','Low albumin and prolonged PT/INR','Albumin changes slowly and has nonhepatic causes; vitamin K deficiency also prolongs PT.'],
 ['Alcohol-associated pattern','AST often exceeds ALT; GGT may rise','A typical pattern, not an absolute ratio or a universal 300 U/L ceiling.'],
 ['Very high aminotransferases','Acute viral, toxic or ischemic injury','ALT can exceed 1000 U/L in acute hepatitis; magnitude alone does not identify a virus.']]),
 p('Total circulating AST has a shorter approximate half-life (about 17-18 hours) than ALT (about 47 hours), so ALT can remain elevated longer after an acute episode; ongoing release and mitochondrial AST complicate the pattern. ALT/AST are PLP-dependent, so B6 deficiency and whether reagent supplies PLP affect measured activity. GGT is membrane associated but is not thereby a GPI-anchored protein; ALP is a classic GPI-anchored enzyme.'),
 p('Dark urine with conjugated bilirubin, pale stools and a cholestatic enzyme pattern indicate impaired bile delivery. Concurrent upper abdominal pain and pancreatic enzyme elevation can suggest biliary pancreatitis, but alcohol history and overlapping patterns prevent certainty without further evaluation. Cystic fibrosis can also cause cholestatic liver disease; an unqualified CF EXCEPT question excluding cholestasis is defective.'),
 box('Function is not synonymous with enzyme leakage','Cirrhosis can lower albumin and prolong coagulation times while bilirubin rises; none of these is a universal exception. Low aminotransferases in advanced disease do not guarantee preserved hepatic function.')
],[book('pp. 128-131; 515-520'),online('Liver Function Tests','https://www.ncbi.nlm.nih.gov/books/NBK482489/'),online('ALT Test: half-life and assay interpretation','https://www.ncbi.nlm.nih.gov/books/NBK559278/'),online('Clinical Methods: Alkaline Phosphatase and GGT','https://www.ncbi.nlm.nih.gov/books/NBK203/')])
new('renal-tests','Renal biochemistry: urea, creatinine, albumin and tubular function',[
 p('Urea contributes most of the usual serum nonprotein nitrogen pool; creatinine, urate, amino acids and ammonia also contain nonprotein nitrogen. Urea production depends on hepatic synthesis and protein catabolism. Creatinine originates from the creatine pool and depends on muscle mass as well as renal removal. Azotemia is the biochemical accumulation of nitrogenous waste; uremia is a clinical syndrome, not its exact synonym.'),
 table(['Test / state','What it asks','Limit'],[
 ['Creatinine-based eGFR','Approximate glomerular filtration from an endogenous marker','Muscle mass, secretion and assay interference matter; normal creatinine does not exclude early disease.'],
 ['Clearance = urine concentration x flow / plasma concentration','A volume of plasma cleared per time','Creatinine clearance modestly overestimates filtration because creatinine is also secreted.'],
 ['Urine albumin/creatinine ratio','Early evidence of glomerular albumin leakage','A spot ratio reduces dilution effects; persistent abnormality needs confirmation.'],
 ['Urine/plasma osmolality','Tubular concentrating performance','Depends on hydration, ADH and medullary gradient; not a uniquely diagnostic injury test.'],
 ['Prerenal volume depletion','Urea can rise disproportionately to creatinine','Vomiting/diarrhea lower perfusion and increase urea reabsorption.'],
 ['GFR below 15 mL/min/1.73 m2','G5 kidney failure range if chronic','A single acute result does not establish chronic ESRD or a dialysis decision.']]),
 p('Creatinine assays include Jaffe and enzymatic methods. Hemoglobin, bilirubin, ketones and other interferents have method-specific effects. A source answer saying high hemoglobin causes falsely low creatinine is not a universal laboratory rule: consult the reagent interference specification. Do not substitute a corrected guessed result for a repeated validated assay.'),
 p('Triamterene blocks epithelial sodium channels in principal cells, reducing sodium entry and potassium secretion, so it is potassium sparing and may cause hyperkalemia. It is not an aldosterone-receptor antagonist. Nephrogenic diabetes insipidus is resistance to vasopressin, including V2-receptor or aquaporin-2 defects; dilute polyuria is a water-handling problem, different from glucose-driven osmotic diuresis.')
],[book('p. 525'),guyton('pp. 356-357, 366-367, 379-380, 426'),online('Renal Function Tests','https://www.ncbi.nlm.nih.gov/books/NBK507821/'),online('Clinical Methods: BUN and Creatinine','https://www.ncbi.nlm.nih.gov/books/NBK305/')])
new('endocrine-signaling','Hormone receptors, second messengers and steroid transport',[
 table(['Hormone / mechanism','Signal','Consequences'],[
 ['Insulin','Receptor tyrosine kinase','Metabolic transport/storage and protein signaling; not a Gs-cAMP receptor.'],
 ['Glucagon; vasopressin V2','Gs -> adenylyl cyclase -> cAMP -> PKA','Hepatic fuel mobilization / collecting-duct aquaporin-2 recruitment.'],
 ['Gq-linked hormones','Phospholipase C -> PIP2 cleavage into IP3 and DAG','IP3 releases stored calcium; DAG activates PKC.'],
 ['Steroid hormones','Intracellular/nuclear receptors','Cholesterol-derived hormones regulate transcription; their effects are not restricted to this one mechanism.'],
 ['Thyroid hormones','Nuclear receptors','Tyrosine-derived amines with lipid-soluble behavior; do not assume every amine uses a surface receptor.'],
 ['NO','Soluble guanylyl cyclase -> cGMP','Smooth-muscle relaxation; distinct from cAMP.']]),
 p('SHBG binds circulating testosterone and estradiol; albumin also contributes transport. Changes in binding protein can change total hormone without the same change in free biologically available hormone. Steroids are largely synthesized on demand rather than stored as mature hormones in secretory granules. Peptide hormones such as insulin are stored in granules. Thyroid hormones are an important exception: they are stored extracellularly in follicular colloid while still part of thyroglobulin.'),
 p('5-alpha-reductase generates DHT from testosterone in androgen-responsive tissues; deficient activity impairs DHT-dependent differentiation and action. It is not the enzyme for cortisol production or estrogen aromatization. In nephrogenic diabetes insipidus, V2 signaling or AQP2 response fails despite available ADH; central diabetes insipidus instead lacks appropriate ADH secretion.')
],[book('pp. 433-447; 562-580'),guyton('pp. 379-380; chapter 75, hormone chemistry and receptors; chapter 81, androgen conversion')])
new('thyroid','Thyroid biochemistry and metabolic laboratory patterns',[
 p('Follicular cells synthesize thyroglobulin, transport iodide into the follicular lumen and use thyroid peroxidase to iodinate its tyrosines. MIT and DIT coupling forms T3 and T4 within the protein. Endocytosis and proteolysis of thyroglobulin release hormones; iodide is recycled from uncoupled iodotyrosines. This differs from storing free peptide hormone inside secretory granules.'),
 table(['State','Typical TSH / free T4','Metabolic interpretation'],[
 ['Overt primary hypothyroidism, including established Hashimoto disease','High TSH / low free T4','Reduced thyroid output removes negative feedback. LDL commonly rises through impaired clearance.'],
 ['Overt primary hyperthyroidism','Suppressed TSH / raised free T4 and/or T3','Increased metabolism and glucose turnover; glucose intolerance may occur, LDL commonly falls.'],
 ['Subclinical or central disorders','Not the same paired pattern','Hashimoto disease can have other phases; low T4 with low/inappropriately normal TSH suggests central dysfunction.']]),
 p('A high-glucose/low-LDL answer in a hyperthyroid exam vignette describes a tendency, not mandatory hyperglycemia in every patient. Likewise HDL does not consistently decrease in hypothyroidism; this makes simplistic triglyceride/HDL EXCEPT questions context dependent.')
],[guyton('pp. 929-940; thyroid synthesis, metabolic effects and feedback'),online('Endotext: Thyroid Hormone Synthesis and Secretion','https://www.ncbi.nlm.nih.gov/books/NBK285550/')])
new('exam-corrections','Past-paper audit: flawed items and conventions to keep separate',[
 p('The available papers test both established metabolism and older clinical-laboratory conventions. Review the mechanism first, then identify exactly what the question asks and which choices were supplied. The app retains original source numbering and differentiates editorial answers from source marks. Twenty-three source items remain ungraded because the choices, wording or evidence do not support one reliable key.'),
 table(['Source problem','Learn instead'],[
 ['No UDP choice for cellulose; reversed succinyl-CoA reaction; no three-disulfide answer for insulin','Cellulose uses UDP-glucose; succinyl-CoA -> succinate yields GTP; insulin has three bridges in total.'],
 ['All listed citrate effects or liver reactions can be true','Citrate inhibits PFK-1, activates ACC and exports acetyl carbon; liver can perform the listed synthesis/oxidation pathways.'],
 ['CF cholestasis excluded; excess hepatic cholesterol assumed to diagnose a disease','CF can cause cholestasis. Cholesterol imbalance establishes accumulation, not a unique diagnosis.'],
 ['Azotemia equated to uremia; all listed NPN compounds actually contain nitrogen','Separate biochemical accumulation from clinical syndrome; classify compounds by nitrogen outside proteins.'],
 ['Universal Gilbert urobilinogen change; all-true neonatal jaundice or cirrhosis EXCEPT lists','Use conjugated/unconjugated fractions and mechanism; do not memorize nonexistent universal exceptions.'],
 ['Unverified SLOS/mevalonic hematology or sotolon differential claims','Use established pathway blocks and disease markers; defer unsupported discriminator claims.'],
 ['MSUD choice missing leucine/ketoacids; brain excluded from creatine synthesis','Teach the actual toxic metabolites and acknowledge extrahepatic creatine synthesis.'],
 ['Ambiguous cataract/AGE, BNP/D-dimer or GPI-anchor wording','Separate polyol from glycation, wall stress from thrombosis, and membrane association from GPI anchoring.']]),
 box('Coverage is not an exam prediction','All source occurrences have a recorded destination in the coverage audit. That includes principles explaining why an item is flawed. It does not turn 23 unresolved questions into scored questions or certify missing lecture content. The separate reconstruction remains an optional supplement.','uncertain')
],[book('pp. 143-155; 246-265; 410-414; 507-555; 562-582')])

SOURCE.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
print(f'Updated {len(v["sections"])} sections; preserved original at {BACKUP}')
