"""Positional OCR import, with explicit reviewed corrections and source provenance.
Input: Vision boxes generated by extract-term1-tissue-ocr.swift.
"""
import json,re,copy,os
from pathlib import Path
import pymupdf as fitz
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'data/term1-telegram/questions';FIG=ROOT/'public/study/term1-telegram/figures'
WORK=Path(os.environ.get('TERM1_TISSUE_WORK_DIR','/tmp'))
SOURCE_OCR=Path(os.environ.get('TERM1_TISSUE_SOURCE_OCR_DIR',str(WORK/'ocr')))
D=json.load(open(WORK/'tissue-ocr-boxes.json'))
def clean(t):return re.sub(r'\s+',' ',t).strip()
def qmake(n,p,prompt,opts):return {'number':n,'sourceOrdinal':n,'page':p,'prompt':clean(prompt),'options':[{'id':chr(65+i),'text':clean(t)} for i,t in enumerate(opts)],'correctOptionId':None,'explanation':'No verified answer key is available for this source question; it is ungraded.','answerBasis':'unresolved','subject':'histology'}
def save(pid,qs,notes):
 d={'paperId':pid,'questions':qs,'notes':notes,'coverage':{'sourcePages':len(fitz.open(ROOT/f'public/study/term1-telegram/{pid}.pdf')),'questionOccurrences':len(qs),'transcribedQuestions':len(qs),'unresolvedAnswers':sum(q['correctOptionId'] is None for q in qs)}}
 (OUT/f'{pid}.json').write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def table2023():
 pid='tissue-2023-annotated';qs=[]
 for d in D:
  if not d['file'].startswith(pid):continue
  pn=int(d['file'][-6:-4]); ls=sorted(d['lines'],key=lambda l:(l['box'][1],l['box'][0]))
  headers=[l for l in ls if l['text'] in ['Histology','Embryology','Physiology']]
  if pn==6:headers.append({'text':'Histology','box':[.141,.237,.23,.255]});headers.sort(key=lambda l:l['box'][1])
  for hi,h in enumerate(headers):
   top=h['box'][1]-.017;end=headers[hi+1]['box'][1]-.017 if hi+1<len(headers) else .98
   content=[]
   for l in ls:
    t=l['text'];x,y,xx,yy=l['box']
    if y<top or y>=end or x<h['box'][0]-.02:continue
    if re.search(r'Question time|histology|^Histology|^Embryology|^Physiology|COUNTINUE|Page|University|Affairs|seconds',t,re.I):continue
    if re.fullmatch(r'[\d\s./|>()→\-]+',t):continue
    t=re.sub(r'^[1-4]\s+(?=[A-Za-z])','',t)
    if len(t)>2:content.append(t)
   n=len(qs)+1
   prompt=' '.join(content[:-4]);opts=content[-4:]
   qs.append(qmake(n,pn,prompt,opts));qs[-1]['subject']=h['text'].lower()
 save(pid,qs,['Alternate annotated scan of the January 2023 question sequence. Handwritten selections are not treated as a verified key.'])
 return qs

def explicit(pid):
 qs=[]
 for d in D:
  if not d['file'].startswith(pid):continue
  pn=int(d['file'][-6:-4]);ls=sorted(d['lines'],key=lambda l:((l['box'][1]+l['box'][3])/2,l['box'][0]))
  starts=[]
  for l in ls:
   m=re.match(r'^(\d{1,2})\s*[.\-)]\s*(.*)',l['text'])
   if m and l['box'][0]<.4:starts.append((l,int(m[1]),m[2]))
  for i,(h,n,stem) in enumerate(starts):
   top=(h['box'][1]+h['box'][3])/2-.008;end=(starts[i+1][0]['box'][1]+starts[i+1][0]['box'][3])/2-.008 if i+1<len(starts) else .98
   ps=[stem];opts={};last=None
   for l in ls:
    if l is h:continue
    t=l['text'];x,y,xx,yy=l['box'];cy=(y+yy)/2
    if cy<top or cy>=end:continue
    if re.search(r'University|Affairs|Campus|Histology:|Embryology:|Physiology:|\|\s*Page|\|\s*Р|TISSUE DEVELOPMENT',t,re.I):continue
    if re.fullmatch(r'[0-9| /→]+',t):continue
    m=re.match(r'^([a-dA-D])\s*[.)\-]\s*(.*)',t)
    if m:opts[m[1].upper()]=m[2];last=m[1].upper()
    elif not opts:ps.append(t)
    elif last:opts[last]+=' '+t
   qs.append(qmake(n,pn,' '.join(ps),[opts.get(a,'[Source option requires transcription]') for a in 'ABCD']))
 save(pid,qs,['Transcribed from original source photographs. Unverified student markings are not used as scored answers.'])
 return qs

def sep2021():
 pid='tissue-sep2021';qs=[]
 raw=json.load(open(SOURCE_OCR/'Tissue Theory SEP2021.json'))
 for p in raw:
  t=re.sub(r'TISSUE DEVELOPMENT & FUNCTIONS THEORY - SEPTEMBER 2021\n','',p['text'])
  ms=list(re.finditer(r'(?m)^(\d+)\s*-\s*',t))
  for i,m in enumerate(ms):
   chunk=t[m.end():ms[i+1].start() if i+1<len(ms) else len(t)]
   ls=[x.strip() for x in chunk.splitlines() if x.strip() and x.strip() not in ['Embryology','Histology','Physiology','/']]
   qs.append(qmake(int(m[1]),p['page'],' '.join(ls[:-4]),ls[-4:]))
 save(pid,qs,['Source report uses printed checkmarks. Diagram crops omit the answer rows.'])
 return qs
if __name__=='__main__':
 table2023();explicit('tissue-sep2019');explicit('tissue-jan2025');sep2021()
 for pid in ['tissue-2023-annotated','tissue-sep2019','tissue-jan2025','tissue-sep2021']:
  qs=json.load(open(OUT/f'{pid}.json'))['questions']
  (WORK/(pid+'-review.txt')).write_text('\n'.join(f"{q['number']} p{q['page']} {q['prompt']}\n"+' | '.join(o['id']+': '+o['text'] for o in q['options']) for q in qs))
  print(pid,len(qs),[q['number'] for q in qs if any('requires transcription' in o['text'] for o in q['options'])])
