"""Render the Biochemistry Retake review as typeset handwritten study notes.

Design: typeset to read like a careful student's colour-ink notes (Zahraa Fawzi's CVS anatomy notes were
the reference): dot-grid paper, coral handwritten headings and numbered key points, blue clinical links,
grey "past paper asked" boxes, a "Test yourself" MCQ box per section with answers upside down, Codex-
generated process figures and precisely computed graphs.

Pipeline: data/biochemistry-retake/review.json (generated by build-biochemistry-retake.mjs) -> HTML ->
headless Chrome PDF -> PyMuPDF post-processing (bookmarks, metadata) -> data/biochemistry-retake/pdf-layout.json
with the exact page and vertical position of every section, concept and past-paper checkpoint paragraph.
Guided mode in the app opens those positions, so every anchored paragraph is kept on a single page.

Run with a Python that has PyMuPDF (fitz). Chrome must be installed. Then rerun
`npm run biochemistry:retake:generate` to publish mappings, anchors and locks.
"""
from pathlib import Path
from html import escape
import hashlib, json, math, os, re, shutil, subprocess, sys, tempfile
import fitz

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data/biochemistry-retake'
SOURCE = DATA / 'review.json'
DEST = ROOT / 'public/study/reviews/biochemistry-retake.pdf'
LAYOUT = DATA / 'pdf-layout.json'
FIGURES = DATA / 'figures'
FONTS = DATA / 'fonts'
BANK = ROOT / 'data/bank/questions/biochemistry-retake.jsonl'
CHROME = os.environ.get('CHROME', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')

data = json.loads(SOURCE.read_text())
sections = data['sections']
for s in sections:
    s.setdefault('unit', 'review'); s.setdefault('unitTitle', 'Biochemistry'); s.setdefault('extension', False)
bank = [json.loads(l) for l in BANK.read_text().splitlines() if l.strip()]
figures = json.loads((FIGURES / 'figures.json').read_text()) if (FIGURES / 'figures.json').exists() else []
figures = [f for f in figures if (FIGURES / f"{f['name']}.jpg").exists()]

def esc(text):
    return escape(str(text)).replace('‑', '-')

# Figures are placed after the concept they explain (fallback: start of their section).
FIG_AFTER = {
    'bicarbonate-buffer': 'water-physiological-buffers-and-compensation',
    'protein-structure-levels': 'ch2-peptide-bond-chemistry-and-planarity',
    'hemoglobin-t-r': 'ch3-cooperativity-tr-and-p50',
    'collagen-synthesis': 'ch4-intracellular-collagen-synthesis',
    'electron-transport-chain': 'ch6-electron-transport-chain',
    'lipid-digestion-absorption': 'ch15-bile-emulsification',
    'carnitine-shuttle-beta-oxidation': 'ch16-fa-entry-carnitine',
    'lipoprotein-metabolism': 'ch18-apo-lipoprotein-map',
    'replication-fork': 'bio-29-leading-lagging-synthesis',
    'mrna-processing': 'bio-30-cap-polyadenylation',
    'translation-ribosome': 'bio-31-ribosome-sites-direction',
    'lac-operon': 'bio-32-lac-operon',
    'pcr-cycle': 'bio-33-pcr-rtpcr',
}
FIG_KEYWORD = {'urea-cycle': 'urea', 'heme-degradation-bilirubin': 'bilirubin'}
CHART_AFTER = {
    'water-titration-buffer-range-and-capacity': 'titration',
    'ch3-myoglobin-versus-hemoglobin': 'oxygen',
    'ch5-michaelis-menten-km-vmax': 'michaelis',
    'ch5-competitive-inhibition': 'lineweaver',
}

# ---------------------------------------------------------------- charts (computed, not drawn by hand)
CORAL, BLUE, INK, GREY = '#e0645b', '#3b7dd8', '#2b2b2b', '#8a8a8a'

def axes(w, h, pad, xlabel, ylabel, xticks, yticks, xr, yr):
    (x0, x1), (y0, y1) = xr, yr
    X = lambda v: pad + (v - x0) / (x1 - x0) * (w - pad - 14)
    Y = lambda v: h - pad + 4 - (v - y0) / (y1 - y0) * (h - pad - 14)
    out = [f'<line x1="{X(x0)}" y1="{Y(y0)}" x2="{X(x1)}" y2="{Y(y0)}" class="ax"/>',
           f'<line x1="{X(x0)}" y1="{Y(y0)}" x2="{X(x0)}" y2="{Y(y1)}" class="ax"/>']
    for v, label in xticks:
        out.append(f'<line x1="{X(v)}" y1="{Y(y0)}" x2="{X(v)}" y2="{Y(y0)+5}" class="ax"/><text x="{X(v)}" y="{Y(y0)+19}" class="tk" text-anchor="middle">{label}</text>')
    for v, label in yticks:
        out.append(f'<line x1="{X(x0)-5}" y1="{Y(v)}" x2="{X(x0)}" y2="{Y(v)}" class="ax"/><text x="{X(x0)-9}" y="{Y(v)+5}" class="tk" text-anchor="end">{label}</text>')
    out.append(f'<text x="{(X(x0)+X(x1))/2}" y="{h-2}" class="al" text-anchor="middle">{xlabel}</text>')
    out.append(f'<text x="14" y="{(Y(y0)+Y(y1))/2}" class="al" text-anchor="middle" transform="rotate(-90 14 {(Y(y0)+Y(y1))/2})">{ylabel}</text>')
    return X, Y, out

def poly(points, X, Y, color, width=2.6, dash=None):
    d = ' '.join(f'{X(x):.1f},{Y(y):.1f}' for x, y in points)
    return f'<polyline points="{d}" fill="none" stroke="{color}" stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"{f" stroke-dasharray={chr(34)}{dash}{chr(34)}" if dash else ""}/>'

def chart(kind):
    w, h, pad = 560, 330, 62
    if kind == 'titration':
        pka = 4.76
        X, Y, out = axes(w, h, pad, 'equivalents of OH⁻ added', 'pH', [(0, '0'), (.5, '0.5'), (1, '1.0')], [(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10')], (0, 1), (2, 10))
        pts = [(x, pka + math.log10(x / (1 - x))) for x in [i / 200 for i in range(2, 197)]]
        pts = [(x, min(max(y, 2.4), 9.6)) for x, y in pts]
        out.append(f'<rect x="{X(0)}" y="{Y(pka+1)}" width="{X(1)-X(0)}" height="{Y(pka-1)-Y(pka+1)}" fill="#3b7dd8" opacity=".10"/>')
        out.append(poly(pts, X, Y, INK))
        out.append(f'<circle cx="{X(.5)}" cy="{Y(pka)}" r="5" fill="{CORAL}"/><text x="{X(.5)+12}" y="{Y(pka)+22}" class="nt" fill="{CORAL}">pH = pKa (4.76): [HA] = [A⁻]</text>')
        out.append(f'<text x="{X(.03)}" y="{Y(pka+1)-8}" class="nt" fill="{BLUE}">buffer range: pKa ± 1</text>')
        out.append(f'<text x="{X(.62)}" y="{Y(3.1)}" class="nt">acetic acid titrated with NaOH</text>')
        cap = 'Weak-acid titration curve, computed from Henderson–Hasselbalch for acetic acid (pKa 4.76). The flat middle is where the buffer resists pH change.'
    elif kind == 'oxygen':
        X, Y, out = axes(w, h, pad, 'PO₂ (mmHg)', 'O₂ saturation (%)', [(0, '0'), (20, '20'), (40, '40'), (60, '60'), (80, '80'), (100, '100')], [(0, '0'), (50, '50'), (100, '100')], (0, 100), (0, 100))
        mb = [(p, 100 * p / (p + 2.8)) for p in [i / 2 for i in range(0, 201)]]
        hb = lambda p50: [(p, 100 * p ** 2.7 / (p ** 2.7 + p50 ** 2.7)) for p in [i / 2 for i in range(0, 201)]]
        out += [poly(mb, X, Y, BLUE), poly(hb(26), X, Y, INK), poly(hb(33), X, Y, CORAL, 2.4, '7 6')]
        out.append(f'<line x1="{X(0)}" y1="{Y(50)}" x2="{X(26)}" y2="{Y(50)}" stroke="{GREY}" stroke-dasharray="3 5"/><line x1="{X(26)}" y1="{Y(50)}" x2="{X(26)}" y2="{Y(0)}" stroke="{GREY}" stroke-dasharray="3 5"/>')
        out.append(f'<text x="{X(5)}" y="{Y(93)}" class="nt" fill="{BLUE}">myoglobin: hyperbolic, P50 ≈ 1–3</text>')
        out.append(f'<text x="{X(27)}" y="{Y(42)}" class="nt">hemoglobin: sigmoid, P50 ≈ 26</text>')
        out.append(f'<text x="{X(44)}" y="{Y(58)}" class="nt" fill="{CORAL}">right shift: ↑H⁺, ↑CO₂, ↑2,3-BPG, ↑temp</text>')
        cap = 'Oxygen-binding curves computed with the Hill equation (Hb n = 2.7). A right shift raises P50 and unloads more O₂ in tissues.'
    elif kind == 'michaelis':
        X, Y, out = axes(w, h, 96, '[S] (substrate concentration)', 'v₀ (initial velocity)', [(0, '0'), (2, 'Km'), (10, ''), (20, '')], [(0, '0'), (.5, 'Vmax/2'), (1, 'Vmax')], (0, 20), (0, 1.1))
        pts = [(s, s / (2 + s)) for s in [i / 10 for i in range(0, 201)]]
        out.append(poly(pts, X, Y, INK))
        out.append(f'<line x1="{X(0)}" y1="{Y(1)}" x2="{X(20)}" y2="{Y(1)}" stroke="{CORAL}" stroke-dasharray="7 6" stroke-width="2"/>')
        out.append(f'<line x1="{X(0)}" y1="{Y(.5)}" x2="{X(2)}" y2="{Y(.5)}" stroke="{GREY}" stroke-dasharray="3 5"/><line x1="{X(2)}" y1="{Y(.5)}" x2="{X(2)}" y2="{Y(0)}" stroke="{GREY}" stroke-dasharray="3 5"/>')
        out.append(f'<text x="{X(7)}" y="{Y(1)-10}" class="nt" fill="{CORAL}">Vmax: enzyme saturated</text>')
        out.append(f'<text x="{X(3)}" y="{Y(.42)}" class="nt">Km = [S] at half Vmax (low Km = high affinity)</text>')
        cap = 'Michaelis–Menten curve v₀ = Vmax[S]/(Km + [S]), computed with Km = 2 and Vmax = 1.'
    else:
        X, Y, out = axes(w, h, pad, '1 / [S]', '1 / v₀', [(-.5, '−1/Km'), (0, '0'), (1, '1'), (1.5, '')], [(1, '1/Vmax'), (4, ''), (8, '')], (-.7, 1.5), (0, 10))
        out.append(f'<line x1="{X(0)}" y1="{Y(0)}" x2="{X(0)}" y2="{Y(10)}" stroke="{INK}" stroke-width="1.2"/>')
        line = lambda km, v, x0: [(x, (km / v) * x + 1 / v) for x in (x0, 1.4)]
        out += [poly(line(2, 1, -.5), X, Y, INK), poly(line(6, 1, -1 / 6), X, Y, CORAL), poly(line(2, .5, -.5), X, Y, BLUE)]
        legend = [(INK, 'no inhibitor', ''), (CORAL, 'competitive', 'same Vmax, ↑Km'), (BLUE, 'noncompetitive', '↓Vmax, same Km')]
        for i, (col, label, note) in enumerate(legend):  # legend sits in its own column right of the plot
            y = 60 + i * 58
            out.append(f'<line x1="580" y1="{y}" x2="612" y2="{y}" stroke="{col}" stroke-width="3.2" stroke-linecap="round"/><text x="620" y="{y+5}" class="nt" fill="{col}">{label}</text>'
                       + (f'<text x="620" y="{y+26}" class="nt" fill="{col}">{note}</text>' if note else ''))
        w_view = 790
        cap = 'Lineweaver–Burk lines computed from 1/v₀ = (Km/Vmax)(1/[S]) + 1/Vmax: competitive inhibitors share the y-intercept, noncompetitive inhibitors share the x-intercept.'
    vb = locals().get('w_view', w)
    svg = f'<svg viewBox="0 0 {vb} {h}" class="chart" role="img">{"".join(out)}</svg>'
    return svg, cap

# ---------------------------------------------------------------- practice MCQs for "Test yourself"
# Questions with more than one defensible option are kept in Practice but never shown in Test yourself.
AMBIGUOUS = {'retake-practice-lippincott-ch1-bank-023-v1'}
def pick_mcqs(section_id, n=3):
    tag = f'review-section-biochemistry-retake/{section_id}'
    pool = [q for q in bank if tag in q.get('tags', []) and q['id'] not in AMBIGUOUS and not q.get('media') and len(q['prompt']) < 230
            and all(len(o['text']) < 120 for o in q['options']) and 3 <= len(q['options']) <= 5]
    pool.sort(key=lambda q: hashlib.sha256(q['id'].encode()).hexdigest())
    seen, out = set(), []
    for q in pool:  # spread across concepts/subtopics
        key = q.get('subtopic') or q.get('chapter')
        if key in seen and len(pool) > n * 2: continue
        seen.add(key); out.append(q)
        if len(out) == n: break
    return out

# ---------------------------------------------------------------- HTML
def font_url(name): return (FONTS / name).as_uri()

CSS = f"""
@font-face{{font-family:'Notes';src:url('{font_url('PatrickHand-Regular.ttf')}')}}
@font-face{{font-family:'Sans';src:url('{(ROOT / 'public/fonts/NotoSans-Regular.ttf').as_uri()}')}}
@font-face{{font-family:'Sans';font-weight:700;src:url('{(ROOT / 'public/fonts/NotoSans-Bold.ttf').as_uri()}')}}
@font-face{{font-family:'Pen';src:url('{font_url('NanumPenScript-Regular.ttf')}')}}
@page{{size:A4;margin:15mm 15mm 17mm 17mm;
  @bottom-right{{content:counter(page);font-family:'Notes';font-size:9pt;color:#9a9a9a}}
  @bottom-left{{content:'MED//25 · biochemistry retake · notes';font-family:'Notes';font-size:8pt;color:#b0b0b0}}}}
@page:first{{@bottom-right{{content:none}}@bottom-left{{content:none}}}}
html{{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
body{{margin:0;font-family:'Notes','Patrick Hand',cursive;font-size:11.4pt;line-height:1.55;color:#1f1f1f}}
.dots{{background:radial-gradient(circle,#d4d8de .55pt,transparent .7pt) 0 0/5.2mm 5.2mm}}
.c{{color:{CORAL}}} .b{{color:{BLUE}}}
h1,h2,h3,.pen{{font-family:'Pen',cursive;font-weight:400;color:{CORAL}}}
/* cover */
.cover{{height:240mm;overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;padding:6mm 2mm}}
.cover .kick{{font-size:13pt;color:#7a7a7a;letter-spacing:.05em}}
.cover h1{{font-size:66pt;line-height:.9;margin:4mm 0 2mm}}
.cover .sub{{font-family:'Pen';font-size:26pt;color:{BLUE};line-height:1.1}}
.cover .units{{columns:2;column-gap:10mm;font-size:12pt;margin-top:6mm}}
.cover .units div{{break-inside:avoid;margin-bottom:2.5mm}}
.cover .units b{{font-family:'Pen';font-weight:400;font-size:19pt;color:{CORAL}}}
.legend{{display:grid;grid-template-columns:auto 1fr;gap:2mm 5mm;font-size:11pt;align-items:center;border-top:1.5px solid #2b2b2b;padding-top:4mm}}
.legend .sw{{font-family:'Pen';font-size:17pt}}
.cover .small{{font-size:9pt;color:#808080;line-height:1.4}}
/* contents */
.toc{{font-family:'Sans',sans-serif}}
.toc h2{{font-family:'Sans',sans-serif;font-weight:700;font-size:24pt;color:#1f1f1f;margin:0 0 4mm}}
.toc .unit{{font-family:'Sans',sans-serif;font-weight:700;font-size:10pt;letter-spacing:.06em;text-transform:uppercase;color:{CORAL};margin:3.5mm 0 .8mm;break-after:avoid}}
.toc .row{{display:flex;gap:2mm;font-size:10.3pt;line-height:1.5;color:#222}}
.toc .row .t{{flex:0 1 auto}}
.toc .row .dl{{flex:1 1 auto;border-bottom:1.5px dotted #b9b9b9;margin-bottom:1.6mm}}
.toc .row .p{{flex:0 0 auto;color:#222;font-variant-numeric:tabular-nums;min-width:8mm;text-align:right}}
.toc .ext{{color:{BLUE};font-size:9.5pt}}
/* compact ideas: title left, points right */
table.ideas{{width:100%;border-collapse:collapse;margin:2mm 0 3mm;font-size:10.8pt;line-height:1.38}}
table.ideas td{{vertical-align:top;border-bottom:1px dashed #cfcfcf;padding:2mm 2mm 2.2mm}}
table.ideas tr{{break-inside:avoid}}
table.ideas td.t{{width:34%;font-family:'Pen';font-size:17pt;line-height:1.02;color:{CORAL}}}
ul.kp{{margin:0;padding:0;list-style:none}}
ul.kp li{{position:relative;padding-left:4.5mm;margin:0 0 .4mm;break-inside:avoid}}
ul.kp li::before{{content:'•';position:absolute;left:.5mm;color:{CORAL}}}
.idea{{margin:4mm 0;break-inside:avoid}}
.idea h3{{font-size:20pt}}
.idea .pair{{display:grid;grid-template-columns:62% 1fr;gap:5mm;align-items:center;font-size:10.6pt;line-height:1.38}}
.idea .pair figure{{margin:0}}
.idea .cols2{{columns:2;column-gap:7mm;font-size:10.6pt;line-height:1.38}}
.fig-only figure img{{max-height:92mm}}
.fig-only.wide figure img,.fig-only figure.wide img{{max-height:110mm;width:auto;max-width:100%}}
table.pp{{width:100%;border-collapse:collapse;font-size:9.8pt;line-height:1.32;margin:1mm 0 3mm}}
table.pp th{{font-family:'Pen';font-weight:400;font-size:15pt;color:#666;border-bottom:1.6px solid #2b2b2b;padding:.8mm 2mm;text-align:left}}
table.pp td{{background:#efefef;border-bottom:2px solid #fbfbfb;padding:1.6mm 2.2mm;vertical-align:top;width:42%}}
table.pp td.ans{{width:58%;color:#333}}
table.pp tr{{break-inside:avoid}}
.tabletitle.grey{{color:#666}}
.srcs{{font-size:8.2pt;color:#9a9a9a;line-height:1.35;margin:3mm 0 0}}
/* section */
.section{{break-before:page}}
.unitstrip{{font-family:'Pen';font-size:17pt;color:{BLUE};border-bottom:1.5px solid #2b2b2b;padding-bottom:1mm;margin-bottom:3mm;display:flex;justify-content:space-between}}
.unitstrip span:last-child{{color:#9a9a9a}}
h2.sec{{font-size:38pt;line-height:.95;margin:2mm 0 1.5mm}}
.basis{{font-size:9.5pt;color:#7a7a7a;margin-bottom:2mm}}
.ext-note{{font-size:10pt;color:{BLUE};border:1.3px dashed {BLUE};border-radius:3mm;padding:1.2mm 3mm;display:inline-block;margin-bottom:3mm}}
.concept{{margin:4mm 0 3mm}}
h3{{font-size:22pt;line-height:1;margin:0 0 1.5mm;break-after:avoid}}
.summary{{margin:0 0 1.5mm;break-inside:avoid}}
ol.kp{{list-style:none;counter-reset:k;margin:0 0 1.5mm;padding:0}}
ol.kp li{{counter-increment:k;display:flex;gap:2mm;align-items:baseline;break-inside:avoid}}
ol.kp li::before{{content:counter(k) '.';flex:0 0 5mm;font-family:'Pen';font-size:16pt;line-height:1;color:{CORAL}}}
.clin{{color:{BLUE};margin:0 0 1mm;break-inside:avoid}}
.clin .pen{{color:{BLUE};font-size:15pt}}
.src{{font-size:8.6pt;color:#9a9a9a;line-height:1.35;margin:0}}
table{{border-collapse:collapse;width:100%;margin:3mm 0 4mm;font-size:10.2pt;line-height:1.35;break-inside:auto}}
th{{font-family:'Pen';font-weight:400;font-size:16pt;color:{CORAL};text-align:left;border-bottom:1.8px solid #2b2b2b;padding:1mm 2mm}}
td{{border-bottom:1px solid #c9c9c9;padding:1.4mm 2mm;vertical-align:top}}
tr{{break-inside:avoid}}
td:first-child{{color:#111}}
.tabletitle{{font-family:'Pen';font-size:19pt;color:{BLUE};margin-top:4mm;break-after:avoid}}
figure{{margin:4mm 0 4mm;break-inside:avoid;text-align:center}}
figure.wide img{{width:100%;max-height:none}}
figure img{{max-width:100%;max-height:96mm;border:1px solid #e3e3e3;border-radius:2mm;background:#fff}}
figure svg.chart{{width:100%;max-width:132mm;height:auto;background:#fff;border:1px solid #e3e3e3;border-radius:2mm}}
figcaption{{font-size:9.6pt;color:#555;margin-top:1.5mm;text-align:left}}
figcaption .pen{{font-size:15pt;margin-right:1.5mm}}
.chart .ax{{stroke:#2b2b2b;stroke-width:1.6}}
.chart .tk{{font-family:'Notes';font-size:15px;fill:#555}}
.chart .al{{font-family:'Notes';font-size:16px;fill:#2b2b2b}}
.chart .nt{{font-family:'Notes';font-size:15.5px;fill:#2b2b2b}}
.quote{{background:#e9e9e9;border:2.2mm solid #fbfbfb;outline:1px solid #d2d2d2;padding:2.5mm 4mm;margin:3mm 0;break-inside:avoid}}
.quote .pen{{font-size:16pt;color:#555;display:block;line-height:1}}
.quote .q{{font-size:10.6pt;color:#333;margin:1mm 0}}
.quote p{{margin:0}}
.quote .src{{margin-top:1mm}}
.test{{background:#f3f3f3;border:1.5px solid #2b2b2b;border-radius:1.5mm;padding:2.5mm 4.5mm;margin:4mm 0 1mm;break-inside:avoid}}
.test .pen{{font-size:22pt;color:{CORAL};line-height:1}}
.test ol{{margin:1.5mm 0 0;padding-left:6mm}}
.test li{{margin-bottom:2mm}}
.test .opts{{display:grid;grid-template-columns:1fr 1fr;gap:0 5mm;font-size:10.2pt;color:#444}}
.answers{{transform:rotate(180deg);text-align:right;font-size:9.6pt;color:#8a8a8a;margin:1mm 0 0}}
.end h2{{font-size:36pt}}
.end li{{margin-bottom:1.5mm}}
"""

def points_html(c, limit=None):
    kp = c.get('keyPoints', [])[:limit] if limit else c.get('keyPoints', [])
    items = ''.join(f'<li>{esc(k)}</li>' for k in kp)
    clin = c.get('clinicalLinks', [])[:1]
    return (f'<ul class="kp">{items}</ul>' if items else '') + ''.join(f'<p class="clin"><span class="pen">→</span> {esc(x)}</p>' for x in clin)

def concept_quote(c, image_only=False):
    """Text Guided mode quotes and the PDF is searched for: the idea's points, or its title when it is shown as an image."""
    return c['title'] if image_only or not c.get('keyPoints') else ' '.join(c['keyPoints'])

# Label-dense diagrams print at full text width so their smallest labels stay readable.
DENSE = {'collagen-synthesis', 'lipoprotein-metabolism', 'replication-fork', 'mrna-processing', 'carbohydrate-metabolism-map', 'electron-transport-chain', 'carnitine-shuttle-beta-oxidation', 'translation-ribosome', 'fed-fast-fuel-flow', 'dna-repair-pathways', 'blotting-and-cloning', 'srp-protein-targeting'}
fig_counter = [0]
DISPLAY = Path(tempfile.gettempdir()) / 'med25-retake-figures'
def display_copy(name):
    """Print-resolution JPEG of a figure (about 220 dpi at 16 cm wide); the PNG originals are untouched."""
    from PIL import Image
    src = FIGURES / f'{name}.jpg'
    out = DISPLAY / f'{name}-{hashlib.sha256(src.read_bytes()).hexdigest()[:12]}.jpg'
    if not out.exists():
        DISPLAY.mkdir(parents=True, exist_ok=True)
        im = Image.open(src).convert('RGB')
        if im.width > 1400: im = im.resize((1400, round(im.height * 1400 / im.width)), Image.LANCZOS)
        im.save(out, 'JPEG', quality=86, optimize=True, progressive=True, subsampling=0)
    return out
def figure_html(fig):
    fig_counter[0] += 1
    cls = ' class="wide"' if fig['name'] in DENSE else ''
    return (f'<figure{cls}><img src="{display_copy(fig["name"]).as_uri()}" alt="{esc(fig.get("alt", fig["caption"]))}">'
            f'<figcaption><span class="pen c">fig. {fig_counter[0]}</span>{esc(fig["caption"])}</figcaption></figure>')

def chart_html(kind):
    fig_counter[0] += 1
    svg, cap = chart(kind)
    return f'<figure>{svg}<figcaption><span class="pen c">fig. {fig_counter[0]}</span>{esc(cap)}</figcaption></figure>'

def figures_for(s):
    """Map each figure to the idea it belongs to (explicit concept, else placement table, else keyword)."""
    owned = {}
    ids = {c['id'] for c in s['concepts']}
    for f in figures:
        target = f.get('concept') or FIG_AFTER.get(f['name'])
        if not target and f['name'] in FIG_KEYWORD:
            target = next((c['id'] for c in s['concepts'] if FIG_KEYWORD[f['name']] in c['id']), None)
        if target in ids: owned.setdefault(target, []).append(f)
    return owned

def section_html(s, pages):
    owned = figures_for(s)
    basis = ('Lippincott 6e, Chapter ' + s['id'][3:]) if s['id'].startswith('ch-') else 'Teacher slides and laboratory material'
    out = [f'<section class="section dots" id="s-{esc(s["id"])}">',
           f'<div class="unitstrip"><span>{esc(s["unitTitle"])}</span><span>{s["order"]:02d}</span></div>',
           f'<h2 class="sec">{esc(s["title"])}</h2><div class="basis">{esc(basis)} · teacher slides</div>']
    for t in s.get('tables', []):
        out.append(f'<div class="tabletitle">{esc(t["title"])}</div><table class="data"><thead><tr>' + ''.join(f'<th>{esc(c)}</th>' for c in t['columns']) + '</tr></thead><tbody>'
                   + ''.join('<tr>' + ''.join(f'<td>{esc(c)}</td>' for c in row) + '</tr>' for row in t['rows']) + '</tbody></table>')
    rows = []
    def flush():
        if rows: out.append('<table class="ideas"><tbody>' + ''.join(rows) + '</tbody></table>'); rows.clear()
    for c in s['concepts']:
        figs = owned.get(c['id'], [])
        chart_kind = CHART_AFTER.get(c['id'])
        if not figs and not chart_kind:
            rows.append(f'<tr id="c-{esc(c["id"])}"><td class="t">{esc(c["title"])}</td><td class="p">{points_html(c)}</td></tr>')
            continue
        flush()
        image_only = any(f.get('concept') == c['id'] for f in figs)  # diagrams drawn to replace the text
        media = ''.join(figure_html(f) for f in figs) + (chart_html(chart_kind) if chart_kind else '')
        dense = any(f['name'] in DENSE for f in figs)
        if image_only:
            out.append(f'<div class="idea fig-only" id="c-{esc(c["id"])}"><h3>{esc(c["title"])}</h3>{media}</div>')
        elif dense:
            out.append(f'<div class="idea" id="c-{esc(c["id"])}"><h3>{esc(c["title"])}</h3>{media}<div class="cols2">{points_html(c)}</div></div>')
        else:
            out.append(f'<div class="idea side" id="c-{esc(c["id"])}"><h3>{esc(c["title"])}</h3><div class="pair"><div>{media}</div><div>{points_html(c)}</div></div></div>')
    flush()
    if s.get('checkpoints'):
        out.append('<div class="tabletitle grey">past papers asked</div><table class="pp"><thead><tr><th>question</th><th>answer and why</th></tr></thead><tbody>'
                   + ''.join(f'<tr id="k-{esc(cp["id"])}"><td>{esc(cp["title"])}</td><td class="ans">{esc(cp["summary"])}</td></tr>' for cp in s['checkpoints']) + '</tbody></table>')
    qs = pick_mcqs(s['id'])
    if qs:
        items = ''.join(f'<li>{esc(q["prompt"])}<div class="opts">' + ''.join(f'<span>{esc(o["id"])}. {esc(o["text"])}</span>' for o in q['options']) + '</div></li>' for q in qs)
        out.append(f'<div class="test"><span class="pen">✎ Test yourself</span><ol>{items}</ol>'
                   f'<p class="answers">answers: ' + ' · '.join(f'{i}&nbsp;{esc(q["correctOptionId"])}' for i, q in enumerate(qs, 1)) + '</p></div>')
    out.append('</section>')
    return ''.join(out)

def build_html(pages):
    fig_counter[0] = 0
    units = []
    for s in sections:
        if not units or units[-1][0] != s['unit']: units.append((s['unit'], s['unitTitle'], []))
        units[-1][2].append(s)
    n_concepts = sum(len(s['concepts']) for s in sections)
    cover = ['<section class="cover dots"><div><div class="kick">MED//25 · Term 1 · Cells &amp; Molecules</div>',
             '<h1>Biochemistry</h1><div class="sub">retake review notes</div>',
             f'<div class="units">' + ''.join(f'<div><b>{esc(t)}</b><br>' + ' · '.join(esc(s['title']) for s in ss) + '</div>' for _, t, ss in units) + '</div></div>',
             '<div><div class="legend"><span class="sw c">coral</span><span>headings, numbered key points, things to learn</span>'
             '<span class="sw b">blue</span><span>clinical links</span>'
             '<span class="sw" style="color:#555">grey box</span><span>a past paper asked this, with the corrected reasoning</span>'
             '<span class="sw c">✎</span><span>Test yourself: three practice MCQs per topic, answers upside down</span></div>',
             f'<p class="small">{len(sections)} topics · {n_concepts} ideas · Lippincott Illustrated Reviews: Biochemistry (Ferrier, 6th ed.) and the teacher slides (Water and Buffer; Amino acids and Proteins; Lipid structure; Enzyme Kinetics; DNA, Transcription, Translation, Gene Regulation; Vitamins; laboratory decks). '
             f'Scope and limits are on the last page. Version {esc(data["version"])}.</p></div></section>']
    toc = ['<section class="toc dots" style="break-before:page"><h2>Contents</h2>']
    for _, t, ss in units:
        toc.append(f'<div class="unit">{esc(t)}</div>')
        for s in ss:
            ext = ' <span class="ext">· practice-bank topic</span>' if s.get('extension') else ''
            toc.append(f'<div class="row"><span class="t">{s["order"]:02d} &nbsp;{esc(s["title"])}{ext}</span><span class="dl"></span><span class="p">{pages.get(s["id"], "00")}</span></div>')
    toc.append('</section>')
    body = ''.join(section_html(s, pages) for s in sections)
    by_topic = ''.join(f'<p class="srcs"><b>{s["order"]:02d} {esc(s["title"])}</b> ' + esc(' · '.join(dict.fromkeys(x for c in s['concepts'] for x in c.get('sourceEvidence', [])))) + '</p>' for s in sections)
    end = ('<section class="section end dots"><h2>Sources and limits</h2><ol>' + ''.join(f'<li>{esc(x)}</li>' for x in data['sources']) +
           '</ol><p>' + esc(data['scope']) + ' Study keys are not certified university keys.</p><p>This review covers the confirmed original biochemistry syllabus and the four imported biochemistry past papers, plus clearly marked practice-bank topics. '
           'It does not certify a new retake announcement or predict future questions. Figures marked as diagrams are teaching illustrations; check details against Lippincott.</p><h3>Sources by topic</h3>' + by_topic + '</section>')
    return f'<!doctype html><html><head><meta charset="utf-8"><title>Biochemistry Retake Review</title><style>{CSS}</style></head><body>{"".join(cover)}{"".join(toc)}{body}{end}</body></html>'

# ---------------------------------------------------------------- render + measure
def print_pdf(html, out):
    with tempfile.TemporaryDirectory() as tmp:
        page = Path(tmp) / 'review.html'; page.write_text(html)
        subprocess.run([CHROME, '--headless=new', '--disable-gpu', '--no-pdf-header-footer', '--allow-file-access-from-files',
                        '--virtual-time-budget=20000', f'--print-to-pdf={out}', page.as_uri()], check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=600)

norm = lambda s: re.sub(r'\W+', '', s).lower()

def locate(doc, texts_norm, quote, start_page=0):
    key = norm(quote)[:100]
    for i in range(start_page, len(doc)):
        if key in texts_norm[i]:
            words = quote.split()[:6]
            hits = doc[i].search_for(' '.join(words)) or doc[i].search_for(' '.join(words[:3]))
            top = hits[0].y0 / doc[i].rect.height if hits else 0.1
            return {'page': i + 1, 'top': round(top, 5)}
    raise AssertionError('Anchor text not found on one page: ' + quote[:80])

def measure(pdf_path):
    doc = fitz.open(pdf_path)
    texts = [norm(p.get_text()) for p in doc]
    sec, con, chk = {}, {}, {}
    for s in sections:
        title = norm(s['title'])
        start = next(i for i in range(2, len(doc)) if any(
            sp['size'] > 30 and norm(sp['text']) and title.startswith(norm(sp['text'])[:20])
            for b in doc[i].get_text('dict')['blocks'] if b['type'] == 0 for l in b['lines'] for sp in l['spans']) and title[:20] in texts[i])
        sec[s['id']] = {'page': start + 1, 'top': 0.07}
        image_only_ids = {f.get('concept') for f in figures if f.get('concept')}
        for c in s['concepts']:
            q = concept_quote(c, c['id'] in image_only_ids)
            con[c['id']] = {**locate(doc, texts, q, start), 'quote': q}
        for cp in s.get('checkpoints', []):
            point = {**locate(doc, texts, cp['summary'], start), 'quote': cp['summary']}
            for qid in cp['questionIds']: chk[qid] = point
    return doc, sec, con, chk

def main():
    DEST.parent.mkdir(parents=True, exist_ok=True)
    draft = DATA / 'tmp-draft.pdf'
    pages = {}
    for attempt in range(3):  # contents page numbers need a second pass
        print_pdf(build_html(pages), draft)
        doc, sec, con, chk = measure(draft)
        new = {k: v['page'] for k, v in sec.items()}
        doc.close()
        if new == pages: break
        pages = new
    doc, sec, con, chk = measure(draft)
    toc = []
    seen_units = set()
    for s in sections:
        if s['unit'] not in seen_units:
            seen_units.add(s['unit']); toc.append([1, s['unitTitle'], sec[s['id']]['page']])
        toc.append([2, s['title'], sec[s['id']]['page']])
    doc.set_toc(toc)
    doc.set_metadata({'title': 'Biochemistry Retake Review - Cells and Molecules', 'author': 'MED25 study review', 'subject': 'Term 1 biochemistry retake notes',
                      'keywords': 'biochemistry, Lippincott, retake, Term 1', 'creator': 'MED25 render-biochemistry-retake.py', 'producer': 'Chrome + PyMuPDF'})
    doc.save(DEST, garbage=4, deflate=True, deflate_images=True, deflate_fonts=True)
    count = len(doc); doc.close(); draft.unlink(missing_ok=True)
    layout = {'sha256': hashlib.sha256(DEST.read_bytes()).hexdigest(), 'manuscriptSha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
              'pageCount': count, 'sections': sec, 'concepts': con, 'checkpoints': chk, 'renderer': 'notes-v2'}
    assert len(sec) == len(sections) and len(con) == sum(len(s['concepts']) for s in sections)
    LAYOUT.write_text(json.dumps(layout, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps({'pages': count, 'sections': len(sec), 'concepts': len(con), 'checkpoints': len(chk), 'figures': fig_counter[0], 'MB': round(DEST.stat().st_size / 1048576, 2)}))

if __name__ == '__main__':
    main()
